import os
import joblib
import numpy as np
import pandas as pd
import tensorflow as tf
import datetime



DATA_FILE = "features_training_dom_mm.csv"

MODEL_FILE = "modelsV2/modebilstm_dommm.keras"
SCALER_X_FILE = "modelsV2/scaler_X.pkl"
SCALER_Y_FILE = "modelsV2/scaler_y.pkl"
FEATURE_COLS_FILE = "modelsV2/feature_columns.pkl"

FORECAST_FILE = "modelsV2/forecast_next_day.csv"

SEQ_LEN = 288
PRED_STEPS = 96


def forecast_next_day(model, scaler_X, scaler_y, feature_cols, df_full):
    df_full = df_full.copy()
    df_full["Timestamp"] = pd.to_datetime(df_full["Timestamp"], errors="coerce")
    df_full = df_full.dropna(subset=["Timestamp"]).sort_values("Timestamp").reset_index(drop=True)

    data_prepared = df_full.drop(columns=["Timestamp", "Unnamed: 0"], errors="ignore")
    X_all = data_prepared.drop(columns=["LoadEnergyCalculated_15"])

    # ensure same columns/order as training
    X_all = X_all.reindex(columns=feature_cols, fill_value=0)

    X_all_scaled = scaler_X.transform(X_all)

    if len(X_all_scaled) < SEQ_LEN:
        raise ValueError(f"Not enough rows for SEQ_LEN={SEQ_LEN}. Got {len(X_all_scaled)}")

    x_input = np.expand_dims(X_all_scaled[-SEQ_LEN:], axis=0)  # (1, seq_len, n_features)

    y_next_scaled = model.predict(x_input)  # (1, 96)
    y_next = scaler_y.inverse_transform(y_next_scaled.reshape(-1, 1)).flatten()

    last_ts = df_full["Timestamp"].iloc[-1]
    future_index = pd.date_range(
        start=last_ts + pd.Timedelta(minutes=15),
        periods=PRED_STEPS,
        freq="15min"
    )

    forecast_df = pd.DataFrame({
        "Timestamp": future_index,
        "LoadEnergyForecast_15": y_next
    })
    forecast_df.to_csv(FORECAST_FILE, index=False)
    return forecast_df


# Load artifacts
model = tf.keras.models.load_model(MODEL_FILE)
scaler_X = joblib.load(SCALER_X_FILE)
scaler_y = joblib.load(SCALER_Y_FILE)
feature_cols = joblib.load(FEATURE_COLS_FILE)

# Load latest features table (regenerated by your feature prep pipeline)
df = pd.read_csv(DATA_FILE)

forecast_df = forecast_next_day(model, scaler_X, scaler_y, feature_cols, df)

print("Saved forecast to:", FORECAST_FILE)
print(forecast_df.head())
